platform :ios, '6.1'
pod 'ObjectiveDDP', :git => 'git@github.com:boundsj/ObjectiveDDP.git', :branch => 'master'
pod 'SocketRocket', :head
pod 'FlatUIKit'
pod 'SDWebImage'
pod 'ASIHTTPRequest'
pod 'SBJson', '3.1'
#pod 'MBProgressHUD'
#pod 'ShareKit/Facebook'
#pod 'ShareKit/GooglePlus'
#pod 'Trovebox-SDK', '4.1.2'
